version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: check packer version
          command: packer version
      - run:
          name: Validate Packer Build File
          command: packer validate ./packer/build.json
  build-image:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build Packer Image
          command: packer build ./packer/build.json
      - store_artifacts:
          path: manifest-snowflake.json
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-image:
          requires:
            - validate
